name: gen_dl_pytorch
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=20.3
  - numpy==1.24.4
  - pandas==2.0.3
  - pillow==10.4.0
  - jupyter==1.1.1
  - huggingface_hub==0.24.6
  - torchinfo==1.8.0
  - torchtext==0.18.0
  - pip:
    - torch==2.1.2+cu118
    - torchvision==0.16.2+cu118
    - matplotlib==3.7.3
    - kaggle==1.6.17 
    - tensorboard==2.14.0 
    - protobuf==3.20.3
    - tokenizers==0.20.1
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - --extra-index-url https://download.pytorch.org/whl/cu118